<function-body> ::= <stmt-compound>
                  | <stmt-arrow>
                  | ";"

<attribs> ::= { <attrib> }
<attrib> ::= CONST

<decl> ::= <decl-function>
         | <decl-variable>

<decl-function>  ::= <attribs> [ EXPORT ] FUNCTION IDENTIFIER "(" [ <decl-parameter> { "," <decl-parameter> } ] ")" [ ":" <type> ] <function-body>
<decl-parameter> ::= IDENTIFIER [ ":" <type> ] [ "=" <expr> ]
<decl-variable>  ::= <attribs> ( EXPORT | LOCAL ) IDENTIFIER [ ":" <type> ] [ "=" <expr> ] ";"

<stmt> ::= <decl>
         | <stmt-compound>
         | ";"

<stmt-arrow>    ::= "=>" <expr> ";"
<stmt-compound> ::= "{" [ <stmt> ] "}"

<type> ::= <type-primitive>

<type-primitive> ::= INT | FLOAT | STRING | BOOL
<type-array>     ::= <type> "[" "]"
<type-table>     ::= <type> "[" <type> "]"

<expr> ::= <expr-lookup>
         | <expr-literal>
         | <expr-binary>

<expr-lookup>  ::= IDENTIFIER
<expr-literal> ::= INTEGER_LITERAL | STRING_LITERAL | TRUE | FALSE
<expr-binary>  ::= <expr> <binary-op> <expr>

<binary-op> ::= "+"
              | "-"
              | "*"
              | "/"
              | "%"
              | "=="
              | "!="
              | "<="
              | ">="
