#ifndef HIBIKU_H
#define HIBIKU_H

#define HBK_STR_HELPER(x) #x
#define HBK_STR(x) HBK_STR_HELPER(x)

#define HBK_VERSION_MAJOR 0
#define HBK_VERSION_MINOR 1
#define HBK_VERSION_BUILD 1

#define HBK_VERSION (HBK_VERSION_MAJOR * 100000) + (HBK_VERSION_MINOR * 1000) + (HBK_VERSION_BUILD)
#define HBK_VERSION_STRING HBK_STR(HBK_VERSION_MAJOR) "." HBK_STR(HBK_VERSION_MINOR) "." HBK_STR(HBK_VERSION_BUILD)

#endif // !HIBIKU_H
